### ISSUE TITLE
ArduCAM CC3200 board schematic missing

### ISSUE THREAD

**Issue by ahha7** [ArduCAM/WIFI_Camera#3]
Hello,

I've bought ArduCAM CC3200 board to use it in my own project, but I can't find schematic of the HW. Could you please upload schematic of the hardware?

Best regards

**Comment by ArduCAM** [comment]
We now are off for Chinese New Year holiday from Feb. 5th to Feb. 16th, so my reply will be delay, please understand.
Please leave me your email address, I will send you as soon as I'm back.

admin@arducam.com

From: ahha7
Date: 2016-02-10 05:25
To: ArduCAM/WIFI_Camera
Subject: [WIFI_Camera] ArduCAM CC3200 board schematic missing (#3)
Hello,
I've bought ArduCAM CC3200 board to use it in my own project, but I can't find schematic of the HW. Could you please upload schematic of the hardware?
Best regards

**Comment by ahha7** [comment]
Hi,

my email is  ahha7@mail.ru  
Happy New Year! )

Best regards,


>Среда, 10 февраля 2016, 7:05 -08:00 от Lee <notifications@github.com>:
>
>We now are off for Chinese New Year holiday from Feb. 5th to Feb. 16th, so my reply will be delay, please understand.
>Please leave me your email address, I will send you as soon as I'm back.
>
>
>
>admin@arducam.com
>
>From: ahha7
>Date: 2016-02-10 05:25
>To: ArduCAM/WIFI_Camera
>Subject: [WIFI_Camera] ArduCAM CC3200 board schematic missing (#3)
>Hello,
>I've bought ArduCAM CC3200 board to use it in my own project, but I can't find schematic of the HW. Could you please upload schematic of the hardware?
>Best regards
>—
>Reply to this email directly or view it on GitHub.
>—
>Reply to this email directly or  view it on GitHub .


Best regards, Valerii Proskurin
